version: '3.7'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 5000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./upload:/usr/share/nginx/html
    networks:
      - xenforo
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: ./php-fpm
    image: xen-php7-fpm
    volumes:
      - ./upload:/usr/share/nginx/html
    networks:
      - xenforo
#  mariadb:
#    image: mariadb:latest
#    ports:
#      - 5002:3306
#    volumes:
#      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
#    networks:
#      - xenforo
networks:
  xenforo: